from . import attendance
from . import school_class
from . import fees
from . import student_dashboard
from . import students
from . import subject
from . import teachers
from . import timetable
from . import school_users
