{
    "name": "School Management",
    "summary": "School Management System",
    "description": "School Management System",
    "author": "Odoo Mates",
    "category": "School",
    "version": "1.0.0",
    "depends": ["base","web"],
    "data": [
        "views/student_dashboard.xml",
        "views/actions.xml",
        "views/menu.xml",
        "security/groups.xml",
        "security/ir.model.access.csv",
        "security/record_rules.xml",
    ],
    "installable": True,
    "application": True,
    "auto-install": False,
    "license": "LGPL-3",
}