from . import Student
from . import Class
from . import Subject
from . import Teacher
from . import Timetable
from . import Attendance
from . import custom_student
from . import student_invoice
from . import notification
from . import res_users
from . import wizard